services:
  frontend:
    image: nginx:alpine
    restart: always
    volumes:
      - ./app-frontend:/usr/share/nginx/html:ro
    ports:
      - "81:80"
  
  backend:
    image: node:18-alpine
    restart: always
    volumes:
      - ./app-backend:/usr/src/app
    ports:
      - "82:3000"
    command: sh -c "chmod +x /usr/src/app/startup.sh && /usr/src/app/startup.sh"
  
  angular-app:
    image: node:18-alpine
    restart: always
    volumes:
      - ./frontend:/usr/src/frontapp
    ports:
      - "4200:4200"
    command: sh -c "chmod +x /usr/src/frontapp/startup.sh && /usr/src/frontapp/startup.sh"